### ISSUE TITLE
tutorial jupyter notebook

### ISSUE THREAD

**Issue by jovo** [neurodata/ndreg-old#1]
1. downloading CLARITY brain from ocp
2. download Allen atlas from ocp
3. rescaling to Allen resolution
4. generating mask
5. mask-LDDMM registration
6. posting allen resolution/orientation version of CLARITY brain back to ocp

is this reasonable for/by hackathon?

**Comment by kkutten1** [comment]
Yes

**Comment by jovo** [comment]
dude, this is so awesome!!!!

**Comment by jovo** [comment]
i presume "inputToken" is not really a token you made, right?

**Comment by kkutten1** [comment]
Yes. The token is inputToken = Control239. Since all the Clarity tokens are private but the repository is public, I replaced it with inputToken.

**Comment by jovo** [comment]
@kkutten1 i deleted the previous comment for obvious reasons :)
