### ISSUE TITLE
create milestones

### ISSUE THREAD

**Issue by jovo** [neurodata/ndreg-old#11]
let's create milestones for when you believe these issues will be complete.
milestone names should be: YYYY_MM_DD

let's restrict milestones to the 15th and the last of the months
eg, 2015_12_31 is a good one that i am using.
2016_01_15 is another good one.

you choose when they will be done, but please do add milestones to each issue.
thank you!

**Comment by kkutten1** [comment]
OK basic plan is 
January - Finish all validation
February - Finish all image analysis (in CLARITYDataAnalysis repo)
March - Finish all Documentation and Webservice

**Comment by jovo** [comment]
cool, let's create the milestones in github later today when i'm there
(12-3).

On Thu, Dec 17, 2015 at 10:24 AM, kkutten1 notifications@github.com wrote:

> Closed #11 https://github.com/openconnectome/ndreg/issues/11.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndreg/issues/11#event-494798246.

## 

the glass is all full:  half water, half air.
neurodata.io
