### ISSUE TITLE
Generate timing results for CLARITY to CLARITY registration comparing CIS To ITK at differnt scales

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndreg-old#19]

**Comment by jovo** [comment]
thanks @kkutten1 can you clarify:
1. you'll make a table?
2. you'll send us a link NLT today?
3. didn't you already do this? i don't see how this will clarify whether it is the integration scheme or the library.  you were going to clarify that for me today, correct?

**Comment by kkutten1** [comment]
| Algorithm | RK4 Scale | Time(s) |
| --- | --- | --- |
| CIS | NA | 4.437 |
| ITK (RK4) | 1.0 | 17.964 |
| ITK (RK4) | 0.5 | 9.025 |
| ITK (RK4) | 0.25 | 1.993 |

RK4 Scale is scale at which Runge-kutta algorithm is run relative to image

**Comment by jovo** [comment]
@kkutten1 please be MUCH more clear.  provide all details you possibly could.
if you provide too many, i'll let you know :)
