### ISSUE TITLE
Use periodic boundary conditons with diffeomorphism

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndreg-old#20]

**Comment by kkutten1** [comment]
Fixed in commit 18d5a1bc7201d2082452937b2592bad0c5b107d7

**Comment by jovo** [comment]
@kkutten1 closing this issue requires demonstrating to mim/nicholas/me that the bug is in fact fixed.
do you have a report demonstrating this?

**Comment by kkutten1** [comment]
@jovo Yes. I'll send it.
