### ISSUE TITLE
The composite lddmm registration

### ISSUE THREAD

**Issue by wujiong-hub** [neurodata/ndreg-old#43]
I had used the imgApplyField function to apply the filed to the labeled atlas, the evaluation result is very bad.  What's the problem here?

**Comment by kkutten1** [comment]
How did you run it?  For label images it's necessary to use nearest neighbor interpolation.

```
outLabelImage = imgApplyField(inLabelImage, field, useNearest=True)
```

**Comment by wujiong-hub** [comment]
The results are still bad after the nearest neighbor interpolation used. Lots of overlap of sub-regions are zero.

**Comment by kkutten1** [comment]
Thanks for for the update.
Could you give me more information?
- Which atlas are you using?  
- What type of subject data are you using?
- Could you post some code outlining how you did the registration?

**Comment by wujiong-hub** [comment]
I used the "m3.img" and "m8.img" in the data set of "CUMC12"(12 subjects were scanned at the Columbia university Medical Center on a 1.5T GE scanner.). Firstly, I used the FLIRT to register m3 to m8 and got m3_to_m8_brain.img, the transformed matrix was also applied to atlas m3_atlas.img and got m3_to_m8_atlas.img.  Then I made m3_to_m8_brain.img as template and m8.img as target to run the  lddmm algorithm. After this process, I got the transformed field which was applied to the m3_to_m8_atlas.img at last. Some code described below:

(field,invField) = imgMetamorphosisComposite(Brain_template,Brain_target,alphaList=[0.01,0.005,0.002],\
                   scaleList = [0.25,0.25,0.25] , iterations = 100, verbose = True, useNearest = True)

Brain_lddmm = imgApplyField(Brain_template, field, size = Brain_target.GetSize(),  useNearest=True)
Atlas_lddmm = imgApplyField(Atlas_template, field, size = Atlas_target.GetSize(), useNearest=True)

imgWrite(Brain_lddmm,'Brain_output_path')
imgWrite(Atlas_lddmm,'Atlas_output_path')


How about the above registration process? I tried lots of time to evaluate the results by using volume overlap and got the answer of majority of regions are zero. I don't know where the problems are?

**Comment by kkutten1** [comment]
Thanks for the detailed response.  You might want try a bigger set of alpha values e.g.
alphaList = [0.05, 0.02, 0.01] and you only have to use nearest neighbor interpolation for label images. Another thing that might be helpful for debugging is to have imgMetamorphosisComposite write all of the output files using the outDirPath parameter.  Therefore in summary...

```
imgMetamorphosisComposite(..., alphaList = [0.05, 0.02, 0.01], useNearest=False, outDirPath="/path/to/output/directory")

Brain_lddmm = imgApplyField(..., useNearest=False)
Atlas_lddmm = imgApplyField(..., useNearest=True)
```
This will create a directory with "step0", "step1", and "step2" subdirectories for the 0.05, 0.02 and 0.01 alpha values.  Each subdirectory has a "log.txt" file.  If you are still having problems could you post these files.

**Comment by KwuJohn** [comment]
Thanks for your response.
But the evaluation results still bad. The log file showed below:

Step 0:
 E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      2.52993e+09, 4354.25, 0, 2.52993e+09 (99.8108%), 1.100000e-03
1.      2.52477e+09, 19077.4, 0, 2.52475e+09 (99.6064%), 1.210000e-03
2.      2.51921e+09, 47060.2, 0, 2.51916e+09 (99.386%), 1.331000e-03
3.      2.51324e+09, 91805.2, 0, 2.51315e+09 (99.1486%), 1.464100e-03
4.      2.50683e+09, 157538, 0, 2.50668e+09 (98.8934%), 1.610510e-03
5.      2.49998e+09, 249335, 0, 2.49973e+09 (98.6195%), 1.771561e-03
6.      2.49267e+09, 373270, 0, 2.49229e+09 (98.326%), 1.948717e-03
7.      2.48488e+09, 536585, 0, 2.48434e+09 (98.0122%), 2.143589e-03
8.      2.4766e+09, 747876, 0, 2.47585e+09 (97.6772%), 2.357948e-03
9.      2.46782e+09, 1.01732e+06, 0, 2.46681e+09 (97.3205%), 2.593742e-03
10.     2.45855e+09, 1.35689e+06, 0, 2.4572e+09 (96.9413%), 2.853117e-03
11.     2.44879e+09, 1.78068e+06, 0, 2.44701e+09 (96.5393%), 3.138428e-03
12.     2.43853e+09, 2.30514e+06, 0, 2.43623e+09 (96.114%), 3.452271e-03
13.     2.4278e+09, 2.94945e+06, 0, 2.42485e+09 (95.6653%), 3.797498e-03
14.     2.41662e+09, 3.73586e+06, 0, 2.41288e+09 (95.1931%), 4.177248e-03
15.     2.40501e+09, 4.69007e+06, 0, 2.40032e+09 (94.6975%), 4.594973e-03
16.     2.39302e+09, 5.84162e+06, 0, 2.38718e+09 (94.179%), 5.054470e-03
17.     2.38069e+09, 7.22432e+06, 0, 2.37347e+09 (93.6381%), 5.559917e-03
18.     2.36809e+09, 8.87665e+06, 0, 2.35921e+09 (93.0756%), 6.115909e-03
19.     2.35528e+09, 1.08421e+07, 0, 2.34444e+09 (92.4929%), 6.727500e-03
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
20.     2.34238e+09, 1.31697e+07, 0, 2.32921e+09 (91.892%), 7.400250e-03
21.     2.32941e+09, 1.59138e+07, 0, 2.31349e+09 (91.272%), 8.140275e-03
22.     2.31637e+09, 1.9135e+07, 0, 2.29724e+09 (90.6306%), 8.954302e-03
23.     2.30349e+09, 2.2897e+07, 0, 2.2806e+09 (89.9741%), 9.849733e-03
24.     2.29075e+09, 2.72673e+07, 0, 2.26349e+09 (89.299%), 1.083471e-02
25.     2.27831e+09, 3.23135e+07, 0, 2.24599e+09 (88.6089%), 1.191818e-02
26.     2.26605e+09, 3.81045e+07, 0, 2.22794e+09 (87.8967%), 1.310999e-02
27.     2.25399e+09, 4.47001e+07, 0, 2.20929e+09 (87.161%), 1.442099e-02
28.     2.24241e+09, 5.21558e+07, 0, 2.19025e+09 (86.4099%), 1.586309e-02
29.     2.23145e+09, 6.05231e+07, 0, 2.17092e+09 (85.6473%), 1.744940e-02
30.     2.22126e+09, 6.98413e+07, 0, 2.15142e+09 (84.8779%), 1.919434e-02
31.     2.21207e+09, 8.01332e+07, 0, 2.13194e+09 (84.1093%), 2.111378e-02
32.     2.20409e+09, 9.13985e+07, 0, 2.11269e+09 (83.3497%), 2.322515e-02
33.     2.19756e+09, 1.0362e+08, 0, 2.09394e+09 (82.6101%), 2.554767e-02
34.     2.19245e+09, 1.16739e+08, 0, 2.07571e+09 (81.891%), 2.810244e-02
35.     2.18871e+09, 1.3065e+08, 0, 2.05805e+09 (81.1944%), 3.091268e-02
36.     2.18641e+09, 1.45206e+08, 0, 2.0412e+09 (80.5295%), 3.400395e-02
37.     2.18553e+09, 1.60241e+08, 0, 2.02529e+09 (79.9017%), 3.740434e-02
38.     2.18549e+09, 1.63999e+08, 0, 2.02149e+09 (79.7518%), 1.028619e-02
39.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.712%), 2.828703e-03
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
40.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.712%), 7.596616e-07
41.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.712%), 2.089069e-07
42.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.7119%), 5.744941e-08
43.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.7119%), 3.949647e-09
44.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.7119%), 2.172306e-09
45.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.7119%), 1.493460e-10
E = 2.18549e+09 (79.7119%)
Length = 10364.6
Time = 422.85s (7.04751m)

Step 1:
 E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      2.04139e+09, 3403.78, 0, 2.04139e+09 (99.8283%), 1.100000e-03
1.      2.03763e+09, 14845.4, 0, 2.03762e+09 (99.6437%), 1.210000e-03
2.      2.03361e+09, 36439.7, 0, 2.03357e+09 (99.4459%), 1.331000e-03
3.      2.02931e+09, 70703.9, 0, 2.02924e+09 (99.2342%), 1.464100e-03
4.      2.02474e+09, 120617, 0, 2.02462e+09 (99.0082%), 1.610510e-03
5.      2.01989e+09, 189683, 0, 2.0197e+09 (98.7677%), 1.771561e-03
6.      2.01476e+09, 282000, 0, 2.01448e+09 (98.5123%), 1.948717e-03
7.      2.00936e+09, 402334, 0, 2.00895e+09 (98.242%), 2.143589e-03
8.      2.00367e+09, 556188, 0, 2.00312e+09 (97.9566%), 2.357948e-03
9.      1.99773e+09, 749882, 0, 1.99698e+09 (97.6565%), 2.593742e-03
10.     1.99154e+09, 990627, 0, 1.99055e+09 (97.3419%), 2.853117e-03
11.     1.98512e+09, 1.28659e+06, 0, 1.98383e+09 (97.0134%), 3.138428e-03
12.     1.97849e+09, 1.64696e+06, 0, 1.97684e+09 (96.6716%), 3.452271e-03
13.     1.97168e+09, 2.08199e+06, 0, 1.9696e+09 (96.3175%), 3.797498e-03
14.     1.96473e+09, 2.60306e+06, 0, 1.96213e+09 (95.9523%), 4.177248e-03
15.     1.95768e+09, 3.22266e+06, 0, 1.95446e+09 (95.5771%), 4.594973e-03
16.     1.95057e+09, 3.95441e+06, 0, 1.94661e+09 (95.1935%), 5.054470e-03
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      2.04139e+09, 3403.78, 0, 2.04139e+09 (99.8283%), 1.100000e-03
1.      2.03763e+09, 14845.4, 0, 2.03762e+09 (99.6437%), 1.210000e-03
2.      2.03361e+09, 36439.7, 0, 2.03357e+09 (99.4459%), 1.331000e-03
3.      2.02931e+09, 70703.9, 0, 2.02924e+09 (99.2342%), 1.464100e-03
4.      2.02474e+09, 120617, 0, 2.02462e+09 (99.0082%), 1.610510e-03
5.      2.01989e+09, 189683, 0, 2.0197e+09 (98.7677%), 1.771561e-03
6.      2.01476e+09, 282000, 0, 2.01448e+09 (98.5123%), 1.948717e-03
7.      2.00936e+09, 402334, 0, 2.00895e+09 (98.242%), 2.143589e-03
8.      2.00367e+09, 556188, 0, 2.00312e+09 (97.9566%), 2.357948e-03
9.      1.99773e+09, 749882, 0, 1.99698e+09 (97.6565%), 2.593742e-03
10.     1.99154e+09, 990627, 0, 1.99055e+09 (97.3419%), 2.853117e-03
11.     1.98512e+09, 1.28659e+06, 0, 1.98383e+09 (97.0134%), 3.138428e-03
12.     1.97849e+09, 1.64696e+06, 0, 1.97684e+09 (96.6716%), 3.452271e-03
13.     1.97168e+09, 2.08199e+06, 0, 1.9696e+09 (96.3175%), 3.797498e-03
14.     1.96473e+09, 2.60306e+06, 0, 1.96213e+09 (95.9523%), 4.177248e-03
15.     1.95768e+09, 3.22266e+06, 0, 1.95446e+09 (95.5771%), 4.594973e-03
16.     1.95057e+09, 3.95441e+06, 0, 1.94661e+09 (95.1935%), 5.054470e-03
17.     1.94345e+09, 4.81304e+06, 0, 1.93863e+09 (94.8032%), 5.559917e-03
18.     1.93636e+09, 5.81433e+06, 0, 1.93055e+09 (94.4079%), 6.115909e-03
19.     1.92937e+09, 6.9751e+06, 0, 1.9224e+09 (94.0093%), 6.727500e-03
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
20.     1.92253e+09, 8.31307e+06, 0, 1.91421e+09 (93.609%), 7.400250e-03
21.     1.91584e+09, 9.84685e+06, 0, 1.90599e+09 (93.207%), 8.140275e-03
22.     1.90936e+09, 1.15959e+07, 0, 1.89777e+09 (92.8048%), 8.954302e-03
23.     1.90307e+09, 1.35807e+07, 0, 1.88949e+09 (92.3999%), 9.849733e-03
24.     1.897e+09, 1.58213e+07, 0, 1.88117e+09 (91.9933%), 1.083471e-02
25.     1.89117e+09, 1.83357e+07, 0, 1.87283e+09 (91.5853%), 1.191818e-02
26.     1.8857e+09, 2.1146e+07, 0, 1.86455e+09 (91.1803%), 1.310999e-02
27.     1.88063e+09, 2.42732e+07, 0, 1.85636e+09 (90.7796%), 1.442099e-02
28.     1.87593e+09, 2.77376e+07, 0, 1.84819e+09 (90.3803%), 1.586309e-02
29.     1.87156e+09, 3.15615e+07, 0, 1.84e+09 (89.9797%), 1.744940e-02
30.     1.86751e+09, 3.57694e+07, 0, 1.83174e+09 (89.5757%), 1.919434e-02
31.     1.86387e+09, 4.03859e+07, 0, 1.82348e+09 (89.172%), 2.111378e-02
32.     1.86064e+09, 4.54372e+07, 0, 1.81521e+09 (88.7674%), 2.322515e-02
33.     1.85775e+09, 5.09522e+07, 0, 1.8068e+09 (88.3562%), 2.554767e-02
34.     1.85521e+09, 5.69561e+07, 0, 1.79826e+09 (87.9385%), 2.810244e-02
35.     1.85312e+09, 6.34735e+07, 0, 1.78964e+09 (87.5173%), 3.091268e-02
36.     1.85146e+09, 7.05355e+07, 0, 1.78092e+09 (87.0908%), 3.400395e-02
37.     1.85023e+09, 7.81751e+07, 0, 1.77206e+09 (86.6573%), 3.740434e-02
38.     1.84955e+09, 8.64207e+07, 0, 1.76313e+09 (86.2206%), 4.114478e-02
39.     1.84947e+09, 9.52978e+07, 0, 1.75418e+09 (85.7829%), 4.525926e-02
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
40.     1.84947e+09, 9.52979e+07, 0, 1.75418e+09 (85.7829%), 3.798308e-07
41.     1.84947e+09, 9.52979e+07, 0, 1.75418e+09 (85.7829%), 1.632085e-09
E = 1.84947e+09 (85.7829%)
Length = 7889.88
Time = 391.931s (6.53219m)

Step 2:
 E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      1.76706e+09, 1604.96, 0, 1.76706e+09 (99.9107%), 1.100000e-03
1.      1.76535e+09, 7031.7, 0, 1.76534e+09 (99.8138%), 1.210000e-03
2.      1.7635e+09, 17346.5, 0, 1.76349e+09 (99.7088%), 1.331000e-03
3.      1.76151e+09, 33843.6, 0, 1.76147e+09 (99.5949%), 1.464100e-03
4.      1.75935e+09, 58087.6, 0, 1.75929e+09 (99.4716%), 1.610510e-03
5.      1.75703e+09, 91963.7, 0, 1.75693e+09 (99.3383%), 1.771561e-03
6.      1.75452e+09, 137735, 0, 1.75439e+09 (99.1942%), 1.948717e-03
7.      1.75184e+09, 198110, 0, 1.75164e+09 (99.0389%), 2.143589e-03
8.      1.74895e+09, 276320, 0, 1.74868e+09 (98.8715%), 2.357948e-03
9.      1.74587e+09, 376209, 0, 1.74549e+09 (98.6914%), 2.593742e-03
10.     1.74257e+09, 502333, 0, 1.74207e+09 (98.4979%), 2.853117e-03
11.     1.73906e+09, 660080, 0, 1.7384e+09 (98.2902%), 3.138428e-03
12.     1.73532e+09, 855799, 0, 1.73446e+09 (98.0678%), 3.452271e-03
13.     1.73135e+09, 1.09695e+06, 0, 1.73025e+09 (97.8298%), 3.797498e-03
14.     1.72715e+09, 1.39227e+06, 0, 1.72576e+09 (97.5755%), 4.177248e-03
15.     1.72272e+09, 1.75196e+06, 0, 1.72096e+09 (97.3045%), 4.594973e-03
16.     1.71805e+09, 2.18788e+06, 0, 1.71586e+09 (97.0161%), 5.054470e-03
17.     1.71316e+09, 2.7138e+06, 0, 1.71044e+09 (96.7097%), 5.559917e-03
18.     1.70805e+09, 3.3456e+06, 0, 1.7047e+09 (96.385%), 6.115909e-03
19.     1.70272e+09, 4.10161e+06, 0, 1.69862e+09 (96.0413%), 6.727500e-03
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
20.     1.69721e+09, 5.00281e+06, 0, 1.69221e+09 (95.6785%), 7.400250e-03
21.     1.69152e+09, 6.07323e+06, 0, 1.68545e+09 (95.2963%), 8.140275e-03
22.     1.68568e+09, 7.34022e+06, 0, 1.67834e+09 (94.8944%), 8.954302e-03
23.     1.67972e+09, 8.83477e+06, 0, 1.67088e+09 (94.4729%), 9.849733e-03
24.     1.67367e+09, 1.05919e+07, 0, 1.66308e+09 (94.0316%), 1.083471e-02
25.     1.66756e+09, 1.26502e+07, 0, 1.65491e+09 (93.5698%), 1.191818e-02
26.     1.66146e+09, 1.50529e+07, 0, 1.64641e+09 (93.089%), 1.310999e-02
27.     1.65544e+09, 1.78482e+07, 0, 1.63759e+09 (92.5906%), 1.442099e-02
28.     1.64955e+09, 2.10868e+07, 0, 1.62846e+09 (92.0745%), 1.586309e-02
29.     1.64385e+09, 2.48202e+07, 0, 1.61903e+09 (91.541%), 1.744940e-02
30.     1.63842e+09, 2.91111e+07, 0, 1.60931e+09 (90.9914%), 1.919434e-02
31.     1.63327e+09, 3.40221e+07, 0, 1.59925e+09 (90.4228%), 2.111378e-02
32.     1.62849e+09, 3.962e+07, 0, 1.58887e+09 (89.8356%), 2.322515e-02
33.     1.62411e+09, 4.59732e+07, 0, 1.57814e+09 (89.2292%), 2.554767e-02
34.     1.62028e+09, 5.31534e+07, 0, 1.56713e+09 (88.6067%), 2.810244e-02
35.     1.61715e+09, 6.12263e+07, 0, 1.55592e+09 (87.9728%), 3.091268e-02
36.     1.6148e+09, 7.02639e+07, 0, 1.54454e+09 (87.3292%), 3.400395e-02
37.     1.61336e+09, 8.03394e+07, 0, 1.53302e+09 (86.6783%), 3.740434e-02
38.     1.61289e+09, 9.15133e+07, 0, 1.52138e+09 (86.0197%), 4.114478e-02
39.     1.61289e+09, 9.1514e+07, 0, 1.52138e+09 (86.0196%), 2.762406e-06
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
40.     1.61289e+09, 9.1514e+07, 0, 1.52138e+09 (86.0196%), 2.967428e-09
41.     1.61289e+09, 9.1514e+07, 0, 1.52138e+09 (86.0196%), 1.632085e-09
E = 1.61289e+09 (86.0196%)
Length = 5527.98
Time = 389.216s (6.48694m)

**Comment by KwuJohn** [comment]
Thanks for your advice. But the evaluation result is the same as before except 2 regions' overlap volume improved. The log file shown below:

Step 0:
         E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      2.52993e+09, 4354.25, 0, 2.52993e+09 (99.8108%), 1.100000e-03
.....
44.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.7119%), 2.172306e-09
45.     2.18549e+09, 1.65008e+08, 0, 2.02048e+09 (79.7119%), 1.493460e-10
E = 2.18549e+09 (79.7119%)
Length = 10364.6
Time = 422.85s (7.04751m)

Step 1:
         E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      2.04139e+09, 3403.78, 0, 2.04139e+09 (99.8283%), 1.100000e-03
......
        E, E_velocity, E_rate, E_image (E_image %), LearningRate
40.     1.84947e+09, 9.52979e+07, 0, 1.75418e+09 (85.7829%), 3.798308e-07
41.     1.84947e+09, 9.52979e+07, 0, 1.75418e+09 (85.7829%), 1.632085e-09
E = 1.84947e+09 (85.7829%)
Length = 7889.88
Time = 391.931s (6.53219m)


Step 2:
 E, E_velocity, E_rate, E_image (E_image %), LearningRate
0.      1.76706e+09, 1604.96, 0, 1.76706e+09 (99.9107%), 1.100000e-03
......
E, E_velocity, E_rate, E_image (E_image %), LearningRate
40.     1.61289e+09, 9.1514e+07, 0, 1.52138e+09 (86.0196%), 2.967428e-09
41.     1.61289e+09, 9.1514e+07, 0, 1.52138e+09 (86.0196%), 1.632085e-09
E = 1.61289e+09 (86.0196%)
Length = 5527.98
Time = 389.216s (6.48694m)

**Comment by wujiong-hub** [comment]
I think I have got the answer of this problem. That may be the problem about format of image in ITK. I read the target atlas by using 'imgRead' and then write it to a file again by using 'imgWrite', then evaluate the overlap volume between lddmm transformed atlas and the above wrote file. At last, I got a  normal evaluation results.

**Comment by kkutten1** [comment]
Good to hear!  I'll close the issue for now.
