### ISSUE TITLE
imgDownload ndreg function requiring .pem file

### ISSUE THREAD

**Issue by toekneesunshine** [neurodata/ndreg-old#49]
We're in the process of updating our ClarityViz registration pipeline and we've noticed that ndreg was recently updated/that many of the brains have been moved.  When we followed this notebook:  https://github.com/neurodata/ndreg/blob/master/doc/s275_Registration.ipynb, we realized that the new imgDownload function requires a "userToken".  We followed the filepath suggested on the CIS server and grabbed a copy of the .pem file, but while trying to do this we get a SSLerror which tells us that the “certificate verify failed”.

Is there some way for us to get our hands on the ara3 reference atlas and the new brains without this userToken .pem file?  If not, is there a way for us to generate a valid version of this .pem file?

@kkutten1 @gkiar

**Comment by kkutten1** [comment]
We've migrated to https servers which require a user token.  To access data you or @alee156 will need to create an account on one of the newer servers (we'll email you its name), log in, and click the "Download User Token" button in the upper right.  Make sure you save the token somewhere as you will only be able to download it once. You will also have to update ndreg and ndio to the latest versions.  @kunallillaney and @Aeusman am I missing anything?

**Comment by Aeusman** [comment]
Not really, just that when you pass the user token, you actually pass the string not the file in the argument. In addition if you are posting data to a channel/project you must own that project, the authentication will fail if you do not (if the project is private). 

That said, if you are getting an SSLError for certificate verify failed I have a feeling that isn't actually an authentication in the backend problem, but a problem with the https credentials of the server you are trying to access. Where are you trying to make calls to?

**Comment by toekneesunshine** [comment]
@Aeusman We were making calls to the reference atlas "ara3" and one of the newer brains "s275" on the dev.neurodata.io server.

Ah, after some tweaking we fixed our problem - I think we had an old version of ndio.  We originally updated ndio through the PyPi package, but after uninstalling and git cloning the repo we managed to fix the issue.  Thanks everybody!

**Comment by matham** [comment]
```
To access data you or @alee156 will need to create an account on one of the newer servers (we'll email you its name), log in, and click the "Download User Token" button in the upper right.
```

How does one create an account? I don't see any place for registering on http://neurodata.io/, and when browsing data I only see a place to login, not register.

**Comment by kkutten1** [comment]
Use https://dev.neurodata.io/nd/ocp/accounts/login/

**Comment by matham** [comment]
Hey, so I registered with the username matham 4-5 days ago. I'm guessing I was supposed to get a activation email afterwards, but it never arrived. I signed up with my edu email, so it could be it got eaten as spam by them, which does happen. 

When I try to sign up again it says that the username is already in use.

**Comment by kkutten1** [comment]
I had the same problem and in my case it was stuck in the spam trap. If you can't find it @Aeusman might be able to help you out.

**Comment by matham** [comment]
That's likely the case, but the issue is that for my edu account it just eats the spam before it's forwarded to my google account so I don't have where to look. Perhaps it'd be better if my registration is deleted so that I can sign up with my normal gmail account.

**Comment by Aeusman** [comment]
@matham I just deleted your account. Please re-register with you gmail and let me know how/if it works out.

**Comment by matham** [comment]
Ok, thanks. I re-registered, but now I get the following when I click on the activation link:

```
Activation Error
Sorry, it didn't work. Either your activation link was wrong, or the key has expired;
```

**Comment by Aeusman** [comment]
I've manually added you to the users group, I'll look into the activation link issue offline.
