### ISSUE TITLE
Write detailed install instructions for ndreg

### ISSUE THREAD

**Issue by kkutten1** [neurodata/ndreg-old#5]

**Comment by jovo** [comment]
i'm pretty satisfied with your notebook.
i'd say the next step is to document everything using Doxygen or Sphinx.
do you know either of those?

**Comment by kkutten1** [comment]
Haven't used them before but I can learn one of them.

**Comment by jovo** [comment]
so, i don't need ITK or FFTW?
should install also install ndio?

**Comment by kkutten1** [comment]
You still need ITK and FFTW to build the binaries.  The main README 
https://github.com/openconnectome/ndreg/blob/master/README.md has 
instructions for installing SimpleITK and refers the user to a 2nd 
readme 
https://github.com/openconnectome/ndreg/blob/master/metamorphosis/src/README.md 
which explains how to build the binary for diffeomorphic registration.  
The install intrusions were written for Linux.  I would need access to a 
Mac to write instructions for that platform.

**Comment by jovo** [comment]
right, the readme does not explicitly mention instructions for ITK, FFTW,
or ndio.  it does mention metamorphasis, but it is unclear what that is.
oh, i see.
ok, just put it all in 1 readme, maybe make clear when each step is
required.
thanks, j

On Sun, Dec 13, 2015 at 1:37 PM, kkutten1 notifications@github.com wrote:

> You still need ITK and FFTW to build the binaries. The main README
> https://github.com/openconnectome/ndreg/blob/master/README.md has
> instructions for installing SimpleITK and refers the user to a 2nd
> readme
> <
> https://github.com/openconnectome/ndreg/blob/master/metamorphosis/src/README.md>
> 
> which explains how to build the binary for diffeomorphic registration.
> The install intrusions were written for Linux. I would need access to a
> Mac to write instructions for that platform.
> 
> On 12/13/2015 01:20 PM, joshua vogelstein wrote:
> 
> > so, i don't need ITK or FFTW?
> > should install also install ndio?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openconnectome/ndreg/issues/5#issuecomment-164285446
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndreg/issues/5#issuecomment-164286489.

## 

the glass is all full:  half water, half air.
neurodata.io
