### ISSUE TITLE
Compute peak RAM consumption for registration as a function of size

### ISSUE THREAD

**Issue by jovo** [neurodata/ndreg-old#7]
perhaps we can register 2 clarity brains together at multiple resolutions,
and profile the code, to get out time, peak RAM, and maybe some other stuff?

@kkutten1 do you know how to do this? if not, we can ask the other guys.

**Comment by kkutten1** [comment]
We can the other guys.

**Comment by kkutten1** [comment]
| Resolution (um) | Size (voxels) | Memory (GB) | Time (hour:min:sec) |
| --- | --- | --- | --- |
| 25 | 576x480x275 | 26.342 | 03:25:08 |
| 50 | 288x240x138 | 3.326 | 00:41:35 |
| 100 | 144x120x69 | 0.475 | 00:10:18 |
| 250 | 58x48x28 | 0.048 | 00:02:52 |

**Comment by jovo** [comment]
that's amazing!!! now to 10 micron?
seems like it might take ~625 GB of RAM and take 3 days?
maybe ask da when a 3 day window exists?
or, ask anthony if there is a 1 TB RAM machine that he has access to?

On Tue, Dec 22, 2015 at 9:28 AM, kkutten1 notifications@github.com wrote:

> Resolution (um) Size (voxels) Memory (GB) Time (hour:min:sec) 25
> 576x480x275 26.342 03:25:08 50 288x240x138 3.326 00:41:35 100 144x120x69
> 0.475 00:10:18 250 58x48x28 0.048 00:02:52
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndreg/issues/7#issuecomment-166629074.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
@kkutten1 why don't you email the stanford guys the table you made, and see what they think?

**Comment by jovo** [comment]
also, did you time affine & rigid as well? 
i presume the above is for mask, rather than image?

**Comment by kkutten1** [comment]
I probably should do the 10 micron first.  Few people should be using 
awesomer over the holiday weekend. I'll ask Da (@icoming) about it

**Comment by kkutten1** [comment]
Yes I used the mask pipeline.  The above times are for the entire pipeline (including affine and rigid).  I don't have times for the affine/rigid but these steps take less than 10 minutes.

**Comment by jovo** [comment]
ok, "the entire pipeline" means that when you do LDDMM, you initialize with
affine, which in turn you have initialized with rigid, yah?

On Wed, Dec 23, 2015 at 5:59 PM, kkutten1 notifications@github.com wrote:

> Yes I used the mask pipeline. The above times are for the entire pipeline
> (including affine and rigid). I don't have times for the affine/rigid but
> these steps take less than 10 minutes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndreg/issues/7#issuecomment-167005629.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by kkutten1** [comment]
Yes, the entire pipeline includes
1. Generating mask for subject
2. Rigid
3. Affine
4. LDDMM

**Comment by jovo** [comment]
you should be sleeping :)

On Thu, Dec 24, 2015 at 5:44 AM, kkutten1 notifications@github.com wrote:

> Yes, the entire pipeline includes
> 1. Generating mask for subject
> 2. Rigid
> 3. Affine
> 4. LDDMM
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ndreg/issues/7#issuecomment-167088634.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by kkutten1** [comment]
Haha so should you..,

**Comment by kkutten1** [comment]
Closing since done
